import streamlit as st
from PIL import Image
import google.generativeai as genai
import base64
from io import BytesIO
import json
from datetime import datetime

# ============== CONFIGURATION ==============
st.set_page_config(
    page_title="Team Trade Analysis",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ============== CUSTOM CSS (RED & BLUE ONLY) ==============
st.markdown("""
<style>
    :root {
        --primary-red: #FF0000;
        --primary-blue: #0000FF;
        --dark-blue: #00008B;
        --light-red: #FF4444;
        --light-blue: #4444FF;
    }
    
    .stApp {
        background: linear-gradient(135deg, #00008B 0%, #0000FF 50%, #FF0000 100%);
    }
    
    .css-1d391kg {
        background-color: #00008B !important;
    }
    
    .stButton>button {
        background-color: #FF0000 !important;
        color: white !important;
        border: 2px solid #0000FF !important;
        border-radius: 10px !important;
        font-weight: bold !important;
    }
    
    .stButton>button:hover {
        background-color: #0000FF !important;
        border: 2px solid #FF0000 !important;
    }
    
    h1, h2, h3 {
        color: #FFFFFF !important;
        text-shadow: 2px 2px 4px #000000;
    }
    
    .stTextInput>div>div>input {
        background-color: #FFFFFF;
        color: #000000;
        border: 2px solid #FF0000;
    }
    
    .stSelectbox>div>div>select {
        background-color: #FFFFFF;
        color: #000000;
        border: 2px solid #0000FF;
    }
    
    .stSuccess {
        background-color: #0000FF !important;
        color: white !important;
        border: 2px solid #FF0000 !important;
    }
    
    .stInfo {
        background-color: #FF0000 !important;
        color: white !important;
        border: 2px solid #0000FF !important;
    }
    
    .stWarning {
        background-color: #FF4444 !important;
        color: white !important;
    }
    
    .stError {
        background-color: #8B0000 !important;
        color: white !important;
    }
    
    /* File uploader fix */
    .stFileUploader {
        background-color: rgba(255, 255, 255, 0.1) !important;
        border: 3px dashed #FF0000 !important;
        border-radius: 15px !important;
        padding: 20px !important;
    }
    
    .stFileUploader > div {
        color: white !important;
    }
    
    .usage-box {
        background-color: #FF0000;
        color: white;
        padding: 10px;
        border-radius: 10px;
        border: 3px solid #0000FF;
        text-align: center;
        font-weight: bold;
    }
</style>
""", unsafe_allow_html=True)

# ============== SESSION STATE ==============
if 'usage_count' not in st.session_state:
    st.session_state.usage_count = 0
if 'max_free_usage' not in st.session_state:
    st.session_state.max_free_usage = 1400
if 'api_key' not in st.session_state:
    st.session_state.api_key = ""
if 'image_data' not in st.session_state:
    st.session_state.image_data = None

# ============== SIDEBAR ==============
st.sidebar.markdown("<h1 style='color: white; text-align: center;'>🔐 LOGIN</h1>", unsafe_allow_html=True)

st.sidebar.markdown("### Enter Gemini API Key")
api_key_input = st.sidebar.text_input(
    "API Key (Get free at makersuite.google.com)",
    type="password",
    value=st.session_state.api_key
)

if api_key_input:
    st.session_state.api_key = api_key_input
    genai.configure(api_key=api_key_input)
    st.sidebar.success("✅ Connected!")

usage_percent = (st.session_state.usage_count / st.session_state.max_free_usage) * 100
st.sidebar.markdown(f"""
<div class="usage-box">
    📊 USAGE: {st.session_state.usage_count} / {st.session_state.max_free_usage}<br>
    ({usage_percent:.1f}%)
</div>
""", unsafe_allow_html=True)

st.sidebar.markdown("---")
st.sidebar.markdown("<h3 style='color: white;'>ℹ️ ABOUT</h3>", unsafe_allow_html=True)
st.sidebar.info("""
**Team Trade Analysis**  
AI-powered chart analysis for all markets.

🔴 **Free Forever** - No payments  
🔵 **1,400 analyses/month**  
🔴 **All markets & timeframes**  
🔵 **Red & Blue theme only**
""")

# ============== MAIN APP ==============
st.markdown("<h1 style='text-align: center; color: white; text-shadow: 3px 3px 6px #FF0000;'>📊 TEAM TRADE ANALYSIS</h1>", unsafe_allow_html=True)
st.markdown("<h3 style='text-align: center; color: #FF0000;'>AI-Powered Chart Analysis | All Markets | All Timeframes</h3>", unsafe_allow_html=True)

# Disclaimer
st.markdown("""
<div style="background-color: #00008B; border: 3px solid #FF0000; padding: 15px; border-radius: 10px; margin: 20px 0;">
    <h4 style="color: #FF0000; margin: 0;">⚠️ DISCLAIMER</h4>
    <p style="color: white; margin: 10px 0 0 0; font-size: 14px;">
    This analysis is generated by AI for educational and informational purposes only. 
    It is not financial advice. Trading involves substantial risk of loss. 
    Always do your own research and consult a licensed financial advisor before trading. 
    Past performance does not guarantee future results.
    </p>
</div>
""", unsafe_allow_html=True)

if not st.session_state.api_key:
    st.warning("🔑 Please enter your Gemini API Key in the sidebar to continue (Free at makersuite.google.com)")
    st.stop()

if st.session_state.usage_count >= st.session_state.max_free_usage:
    st.error("🚫 Monthly free limit reached (1,400 analyses). Please wait until next month.")
    st.stop()

# ============== INPUT SECTION ==============
st.markdown("---")
st.markdown("<h2 style='color: white;'>📸 UPLOAD YOUR CHART</h2>", unsafe_allow_html=True)

col1, col2 = st.columns(2)

with col1:
    st.markdown("### 1. Select Market")
    market_type = st.selectbox(
        "Market Type",
        ["Forex", "Crypto", "Stocks", "Indices", "Commodities", "Futures", "Options"]
    )
    
    if market_type == "Forex":
        symbol = st.text_input("Currency Pair (e.g., EURUSD, GBPJPY)", "EURUSD").upper()
    elif market_type == "Crypto":
        symbol = st.text_input("Crypto Pair (e.g., BTCUSD, ETHUSD)", "BTCUSD").upper()
    elif market_type == "Stocks":
        symbol = st.text_input("Stock Symbol (e.g., AAPL, TSLA)", "AAPL").upper()
    else:
        symbol = st.text_input("Symbol/Contract", "XAUUSD").upper()

with col2:
    st.markdown("### 2. Select Timeframe")
    timeframe = st.selectbox(
        "Timeframe",
        ["1 Minute", "5 Minutes", "15 Minutes", "30 Minutes", 
         "1 Hour", "4 Hours", "Daily", "Weekly", "Monthly"]
    )
    
    st.markdown("### 3. Upload Chart Image")
    
    # SIMPLIFIED FILE UPLOADER FOR MOBILE
    uploaded_file = st.file_uploader(
        "Click to upload chart image (PNG, JPG, JPEG)",
        type=['png', 'jpg', 'jpeg'],
        accept_multiple_files=False,
        help="Upload a screenshot of your trading chart"
    )

# ============== ANALYSIS SECTION ==============
if uploaded_file is not None:
    st.markdown("---")
    
    try:
        image = Image.open(uploaded_file)
        st.session_state.image_data = image
        
        col1, col2 = st.columns([1, 1])
        
        with col1:
            st.markdown("<h3 style='color: white;'>📊 YOUR CHART</h3>", unsafe_allow_html=True)
            st.image(image, use_column_width=True, caption=f"{symbol} | {timeframe}")
        
        with col2:
            st.markdown("<h3 style='color: white;'>🔍 TRADE DETAILS</h3>", unsafe_allow_html=True)
            st.markdown(f"""
            <div style="background-color: #00008B; border: 2px solid #FF0000; padding: 15px; border-radius: 10px;">
                <p style="color: white; font-size: 16px;"><strong>Market:</strong> {market_type}</p>
                <p style="color: white; font-size: 16px;"><strong>Symbol:</strong> {symbol}</p>
                <p style="color: white; font-size: 16px;"><strong>Timeframe:</strong> {timeframe}</p>
                <p style="color: white; font-size: 16px;"><strong>Date:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M')}</p>
            </div>
            """, unsafe_allow_html=True)
            
            analyze_button = st.button("🚀 ANALYZE CHART NOW", use_container_width=True)
        
        # ============== AI ANALYSIS ==============
        if analyze_button:
            with st.spinner("🔍 AI is analyzing your chart... Please wait..."):
                try:
                    buffered = BytesIO()
                    image.save(buffered, format="PNG")
                    img_bytes = buffered.getvalue()
                    
                    prompt = f"""
                    You are an expert technical analyst. Analyze this {market_type} chart for {symbol} on the {timeframe} timeframe.
                    
                    Provide a detailed analysis in this exact format:
                    
                    **TREND DIRECTION:** [Bullish/Bearish/Neutral with confidence percentage]
                    
                    **KEY LEVELS:**
                    - Support: [price levels]
                    - Resistance: [price levels]
                    
                    **PATTERN RECOGNITION:** [Any chart patterns detected or "None detected"]
                    
                    **TECHNICAL INDICATORS:** [What indicators suggest based on price action]
                    
                    **POTENTIAL SETUP:**
                    - Suggested Entry: [price or range]
                    - Stop Loss: [price]
                    - Take Profit: [price]
                    - Risk:Reward Ratio: [ratio]
                    
                    **CONFIDENCE SCORE:** [0-100%]
                    
                    **ANALYSIS SUMMARY:** [2-3 sentence summary]
                    
                    Remember: This is educational analysis only. Trading involves risk.
                    """
                    
                    model = genai.GenerativeModel('gemini-1.5-flash')
                    response = model.generate_content([prompt, image])
                    
                    st.session_state.usage_count += 1
                    
                    st.markdown("---")
                    st.markdown("<h2 style='color: #FF0000; text-align: center;'>🎯 AI ANALYSIS RESULTS</h2>", unsafe_allow_html=True)
                    
                    analysis_text = response.text
                    
                    st.markdown(f"""
                    <div style="background-color: #00008B; border: 4px solid #FF0000; border-radius: 15px; padding: 25px; margin: 20px 0;">
                        <pre style="color: white; font-size: 15px; white-space: pre-wrap; font-family: Arial;">{analysis_text}</pre>
                    </div>
                    """, unsafe_allow_html=True)
                    
                    col1, col2, col3 = st.columns(3)
                    with col1:
                        if st.button("🔄 Analyze Another Chart"):
                            st.session_state.image_data = None
                            st.rerun()
                    with col2:
                        st.download_button(
                            label="📥 Download Analysis",
                            data=f"Team Trade Analysis\n{symbol} | {timeframe} | {datetime.now()}\n\n{analysis_text}",
                            file_name=f"{symbol}_{timeframe}_analysis.txt",
                            mime="text/plain"
                        )
                    with col3:
                        if st.button("📋 Copy to Clipboard"):
                            st.success("Analysis copied! (Simulated)")
                    
                    st.balloons()
                    st.success(f"✅ Analysis complete! Remaining: {st.session_state.max_free_usage - st.session_state.usage_count}")
                    
                except Exception as e:
                    st.error(f"❌ Error during analysis: {str(e)}")
                    st.info("💡 Tip: Check your API key and internet connection.")
                    
    except Exception as e:
        st.error(f"❌ Error loading image: {str(e)}")
        st.info("💡 Please try a different image file (PNG, JPG, or JPEG)")

# ============== FOOTER ==============
st.markdown("---")
st.markdown("""
<div style="text-align: center; padding: 20px; background-color: #00008B; border-top: 3px solid #FF0000;">
    <p style="color: white; font-size: 14px;">
        <strong>Team Trade Analysis</strong> | Built with ❤️ using Streamlit & Google Gemini<br>
        🔴 Free Forever | 🔵 No Hidden Fees | 🔴 Educational Purpose Only
    </p>
    <p style="color: #FF0000; font-size: 12px;">
        © 2024 Team Trade Analysis. Not financial advice. Trade at your own risk.
    </p>
</div>
""", unsafe_allow_html=True)
